### ISSUE TITLE
styles.css not specific enough

### ISSUE THREAD

**Issue by danmarsden** [brickfield/moodle-mod_board#1]
in your styles.css you define a number of generic styles that could clash with core moodle code or other locations where simliar names are used. 
eg:
https://github.com/brickfield/moodle-mod_board/blob/main/styles.css#L114

probably need to be prefixed with .mod_board

Please make sure your css classes in styles.css are specific enough so they cannot clash with other core code.

**Comment by mchurchward** [comment]
Handled https://github.com/brickfield/moodle-mod_board/commit/7a0965a47d89a3823c17a401d9d93b7c4510484f
