### ISSUE TITLE
featuerrequest: Show author of comment

### ISSUE THREAD

**Issue by andreasschenkel** [brickfield/moodle-mod_board#100]
At the moment the comments on notes do not include the name of the user who has added a comment.
There should be a setting in every board activity to activate or deactivate if the name of a user should be show in a comment.
--> Feedback welcome
--> Development in progress
![grafik](https://github.com/brickfield/moodle-mod_board/assets/31856043/45795f70-97c5-4d94-b620-4ff12f30b93e)

**Comment by learningtechnologyservices** [comment]
Hi Andrea, please refer to [Issue #25](https://github.com/brickfield/moodle-mod_board/issues/25) for further details on this discussion.

**Comment by andreasschenkel** [comment]
I think that this pull request does not lead to https://github.com/brickfield/moodle-mod_board/issues/25 #25. This pull request "only" adds the autor of comments. 
I think "posts" in #25 means the added notes to the columns of the board.
Is this correct or am I wrong?

Will try to start developing #25 soon.
