### ISSUE TITLE
improvement: do not add content to log

### ISSUE THREAD

**Issue by andreasschenkel** [brickfield/moodle-mod_board#101]
In board.php log-functions like board_add_note_log do include the content of a note.
Add a setting eg "includecontentinlog" to activate or deactivate logging of content (eg set content to "" if includecontentinlog=false)
--> Feedback welcome
--> Development is in progress

**Comment by learningtechnologyservices** [comment]
[Merged here](https://github.com/brickfield/moodle-mod_board/commit/1387a5d456303ef42e78f4f9485c9d387a246fa8), closing. Thanks for your contribution @andreasschenkel !
