### ISSUE TITLE
Access to course menu items breaks wwith Single Activity and mod_board

### ISSUE THREAD

**Issue by ralfhilg** [brickfield/moodle-mod_board#107]
Create a new course
Select Single activity course format
Select Board as activity
Add a title for board
Board will be created an can be editied.
Select one of the items of the course menu
Error message
Warning: Attempt to read property "context" on null in /home/vhosts/moodle/162206.logineonrw-lms.de/public_html/mod/board/lib.php on line 206 

Additional information
mod_board 1.400.01 (Build 2022101201) 2022040105
Moodle Version 4.1.5
PHP 8.1.21
PostgreSQL 13.13

Additional information from debud mode

Fehler: has_capability(): Argument #2 ($context) must be of type context, null given, called in [dirroot]/mod/board/lib.php on line 206 

Debug an
Deprecated: Implicit conversion from float 316.0000000000002 to int loses precision in /home/vhosts/moodle/162206.logineonrw-lms.de/public_html/course/format/tiles/settings.php on line 198

Deprecated: Implicit conversion from float 317.0000000000002 to int loses precision in /home/vhosts/moodle/162206.logineonrw-lms.de/public_html/course/format/tiles/settings.php on line 198 

Warning: Attempt to read property "context" on null in /home/vhosts/moodle/162206.logineonrw-lms.de/public_html/mod/board/lib.php on line 206 

Debug info: 
Error code: generalexceptionmessage
Stack trace: 
    • line 427 of /lib/accesslib.php: TypeError thrown
    • line 206 of /mod/board/lib.php: call to has_capability()
    • line 4880 of /lib/navigationlib.php: call to board_extend_settings_navigation()
    • line 4342 of /lib/navigationlib.php: call to settings_navigation->load_module_settings()
    • line 833 of /lib/pagelib.php: call to settings_navigation->initialise()
    • line 962 of /lib/pagelib.php: call to moodle_page->magic_get_settingsnav()
    • line 1124 of /lib/classes/navigation/views/secondary.php: call to moodle_page->__get()
    • line 214 of /lib/classes/navigation/views/secondary.php: call to core\navigation\views\secondary->load_single_activity_course_navigation()
    • line 890 of /lib/pagelib.php: call to core\navigation\views\secondary->initialise()
    • line 962 of /lib/pagelib.php: call to moodle_page->magic_get_secondarynav()
    • line 70 of /theme/boost/layout/drawers.php: call to moodle_page->__get()
    • line 1477 of /lib/outputrenderers.php: call to include()
    • line 1403 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
    • line 101 of /user/index.php: call to core_renderer->header()

**Comment by brickfieldlabs** [comment]
This is noted and will be sorted in next release.

**Comment by learningtechnologyservices** [comment]
Hi Ralf!

Following your text steps, and I couldn't replicate your error. The board activity appeared ok and all the course menu options behaved ok.

Would it be possible to get the course as a backup, so we could investigate further please?

![board single activity course, looks ok](https://github.com/brickfield/moodle-mod_board/assets/4713457/082c5b51-cf7c-4ea1-9638-d5ebf5c05548)

**Comment by learningtechnologyservices** [comment]
Hi @ralfhilg , we have a [new default 4.1 branch for Board on github](https://github.com/brickfield/moodle-mod_board/tree/MOODLE_401_STABLE), which includes many bug fixes, including for this one.

However, from your version details, it looks like your installation used the MOODLE_400_STABLE branch instead, which does not include most of our bug fixes.

Also, we have been delayed getting this onto the Moodle plugins database, as a new release, due to an issue with 4.2 needing correct event naming (this is also the reason for the CI failures), and our events are currently not following this. We'll see if we can release an up-to-date 4.1 board release in the meantime.

**Comment by ralfhilg** [comment]
Thank you.

**Comment by learningtechnologyservices** [comment]
Hi @ralfhilg , we have released our [new version of Board](https://moodle.org/plugins/mod_board) for 4.00, 4.01, and 4.02 in the Moodle plugins database. We're confident this should fix your reported issue!
