### ISSUE TITLE
Need to remove from event classes the method get_legacy_logdata for Moodle 4.2 

### ISSUE THREAD

**Issue by pmaneggia** [brickfield/moodle-mod_board#112]
Starting with Moodle 4.2 all of the following tests cause an error `Unexpected debugging() call detected`

- mod_board\board_test::test_board_add_column
- mod_board\board_test::test_board_update_column
- mod_board\board_test::test_board_delete_column
- mod_board\board_test::test_get_note_file
- mod_board\board_test::test_board_add_note
- mod_board\board_test::test_board_update_note
- mod_board\board_test::test_board_delete_note
- mod_board\board_test::test_board_move_note
- mod_board\board_test::test_board_rate_note
- mod_board\board_test::test_board_completion

This is because the related events define the method `get_legacy_logdata`

**Comment by learningtechnologyservices** [comment]
Hi there, thanks for the issue report, this has been fixed with [commit fb53f6c](https://github.com/brickfield/moodle-mod_board/commit/fb53f6c0096d152c34d9c033abe4f0f48417d098).
