### ISSUE TITLE
 featuerrequest: Show author of note

### ISSUE THREAD

**Issue by andreasschenkel** [brickfield/moodle-mod_board#116]
Add an admin setting to be able to activate the functionality to show the author of a note on the board.
If activated for the moodle site then a teacher can configure the board to show or hide the auhor of  a note.
At top of the board an information shows the user if the setting is activated. If the setting is not activated, then this information gives the user a hint, that the author might later set to be visible (teachers can already get the information who added a note by exporting the notes).
Development is in progress.

**Comment by andreasschenkel** [comment]
Still WIP!

**Comment by learningtechnologyservices** [comment]
Hi Andreas, to address concerns over users' awareness of the privacy of their submitted Board content, we have added a [configurable privacy statement here](https://github.com/brickfield/moodle-mod_board/commit/51fe87029b04dd66c9bb6ccd1bb9185ba9ec3ddd) to appear under the board description. 

We do feel that students should be already realistically aware that their actions are not anonymous on a Moodle site; the anonymity we describe in our Board overview is really dealing with student to student viewing.

We hope this meets your concerns.
