### ISSUE TITLE
mod_board fit for moodle 4.3

### ISSUE THREAD

**Issue by nolowolf** [brickfield/moodle-mod_board#129]
We are using board very regularly and it would be nice if it were developed for moodle 4.3

**Comment by learningtechnologyservices** [comment]
Hi there, thanks for your kind feedback! We are hoping to fix this issue shortly, with the [PR 110 here](https://github.com/brickfield/moodle-mod_board/pull/110), kindly provided by [Matthias Opitz](https://github.com/opitz), we just need to code review and release it first.

**Comment by sh-csg** [comment]
#127 also contains 4.3 fixes

**Comment by learningtechnologyservices** [comment]
@sh-csg many thanks for your 4.3 fix which has been merged, and we will test and merge the activity completion issue next.

**Comment by learningtechnologyservices** [comment]
[Matthias Opitz](https://github.com/opitz), many thanks for your 4.3 fix for default activity completion, which has now been merged.
