### ISSUE TITLE
Board does not show on activity report

### ISSUE THREAD

**Issue by ehoving** [brickfield/moodle-mod_board#130]
Hi we are noticing on Moodle 4.3 the Boards activity is not showing up on Moodle's activity report.

Is this a known issue?

Thanks!

**Comment by learningtechnologyservices** [comment]
Hi there, we are hoping to fix this issue shortly, with the [PR 110 here](https://github.com/brickfield/moodle-mod_board/pull/110), kindly provided by [Matthias Opitz](https://github.com/opitz), we just need to code review and release it first.

**Comment by learningtechnologyservices** [comment]
This should now be resolved with [commit 84f5b00 here](https://github.com/brickfield/moodle-mod_board/commit/84f5b00ee3cfc34b14ec7245124011a7c5718521), thanks for your support.
