### ISSUE TITLE
Bug: Board embedded to the course page - Name/Title is visible twice

### ISSUE THREAD

**Issue by peho72** [brickfield/moodle-mod_board#135]
Hi,
The bug in title is at least on the versions: 1.401.02 and 1.401.03
Earlier version 1.400.something was fine.
Edit: Title is fine, when board is not embedded to course main page but opens new view to the board (settings: not tag on embedded box.

Picture 1.401.02 embedded board on the course main page:
![board-bug-in-title](https://github.com/brickfield/moodle-mod_board/assets/125540658/5e1a25d1-555b-43c6-9479-a23595cf3be8)

A teacher pointed us this bug in form of a question: "How you can change this to show title only once?"

Thanks for looking this and possibly show the title again only once, please.

**Comment by learningtechnologyservices** [comment]
Dealt with by adding the hideheader setting for each board instance in [this commit here](https://github.com/brickfield/moodle-mod_board/commit/6eb00aea8e5eb7cd98834470e4e5d2056bdddf99), closing. Thanks for reporting this issue @peho72 !

**Comment by peho72** [comment]
So the translations English version of optional hiding header is "Hide embedded board name (needed on some themes)". Thanks.
