### ISSUE TITLE
Unhandled exception on very first callback

### ISSUE THREAD

**Issue by sharpchi** [brickfield/moodle-mod_board#14]
On a freshly installed Board, the very first ajax request throws an exception if you have no content.
![image](https://user-images.githubusercontent.com/3774280/130926050-4e8d4856-527f-446f-88c9-ad9180e38573.png)

Steps to reproduce:
1. Install mod_board - default settings
2. Add a board to a course
3. wait 60 seconds (i.e. don't load any content)

**Comment by mchurchward** [comment]
There is a new release today. Please check with this one.

**Comment by sharpchi** [comment]
That seems fixed! Thanks Mike
