### ISSUE TITLE
php 8.2 dynamic property deprecated on class board_table

### ISSUE THREAD

**Issue by steveorulez** [brickfield/moodle-mod_board#140]
Hello,
on the export page you can see these errors (when debug is enabled) and you can't export the csv

Deprecated: Creation of dynamic property mod_board\tables\board_table::$boardid is deprecated in mod/board/classes/tables/board_table.php on line 53
Deprecated: Creation of dynamic property mod_board\tables\board_table::$groupid is deprecated in mod/board/classes/tables/board_table.php on line 54
Deprecated: Creation of dynamic property mod_board\tables\board_table::$includedeleted is deprecated in mod/board/classes/tables/board_table.php on line 55
Deprecated: Creation of dynamic property mod_board\tables\board_table::$ownerid is deprecated in mod/board/classes/tables/board_table.php on line 56
Deprecated: Creation of dynamic property mod_board\tables\board_table::$hasrating is deprecated in mod/board/classes/tables/board_table.php on line 57

Add these on the class board_table
    protected $boardid;
    protected $groupid;
    protected $includedeleted;
    protected $ownerid;
    protected $hasrating;

christian

**Comment by learningtechnologyservices** [comment]
Hi @steveorulez , many thanks for giving us a detailed report of this issue, and we will aim to have it resolved shortly. Regards Karen

**Comment by learningtechnologyservices** [comment]
This has been fixed in [this commit here](https://github.com/brickfield/moodle-mod_board/commit/fae55c429fd7fd081593a82d0da117f3edbee984), closing.
