### ISSUE TITLE
Add teacher moderation

### ISSUE THREAD

**Issue by emmarichardson** [brickfield/moodle-mod_board#141]
It would be powerful if teachers had the option to moderate postings.  This would avoid any inappropriate postings.

**Comment by brickfieldlabs** [comment]
Hi Emma,

That sounds like a reasonable feature.  We generally only add features where an organisation has donated to the roadmap, to cover at least their feature and contributing to general roadmap.

please contact us directly  if you want to organise a PO/Invoice to contribute.

Regards
Gavin
