### ISSUE TITLE
Icon display

### ISSUE THREAD

**Issue by livvyfox** [brickfield/moodle-mod_board#15]
On Boost theme Moodle 3.9,  the star and delete icon for each of the posts display over the post text. This makes it difficult to read the text.
First time posting on GitHub, so let me know if am posting in the wrong place or if you need more info.
![board icons](https://user-images.githubusercontent.com/89640584/131123810-b710c3d9-ede7-4699-8db4-4fda8c4a33ad.PNG)

**Comment by learningtechnologyservices** [comment]
We have been changing the icon layout, as per latest release and next one will finalise so this does not happen at all - once we move edit to icon, too./
