### ISSUE TITLE
error/formsubmissioninvalid when posting content higher than 255 character

### ISSUE THREAD

**Issue by christina-roperto** [brickfield/moodle-mod_board#19]
How to replicate: 

1. go to site/admin/settings.php?section=modsettingboard and set `post_max_length` to 1000;
2. create a new post and it will open `New post for column Heading`
3. paste more than 255 characters on the content. Eg: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tellus orci ac auctor augue mauris augue neque gravida. Amet mauris commodo quis imperdiet massa. Suscipit tellus mauris a diam maecenas sed enim ut.`
4.  You will see this message below:
```
Error code: formsubmissioninvalid
$a contents: 
* line 349 of /mod/board/external.php: moodle_exception thrown
* line 261 of /lib/externallib.php: call to mod_board_external::submit_form()
* line 81 of /lib/ajax/service.php: call to external_api::call_external_function()
```

I will create a PR for this :)

**Comment by pierpaolo17** [comment]
Same error with a very short post (title and content 4 chars) 
File: /mod/board/external.php 
line: 397

Error code: formsubmissioninvalid
$a contents: 
* line 397 of /mod/board/external.php: moodle_exception thrown
* line 261 of /lib/externallib.php: call to mod_board_external::submit_form()
* line 81 of /lib/ajax/service.php: call to external_api::call_external_function()

**Comment by simpasami** [comment]
> Same error with a very short post (title and content 4 chars) File: /mod/board/external.php line: 397
> 
> Error code: formsubmissioninvalid $a contents:
> 
> * line 397 of /mod/board/external.php: moodle_exception thrown
> * line 261 of /lib/externallib.php: call to mod_board_external::submit_form()
> * line 81 of /lib/ajax/service.php: call to external_api::call_external_function()

We had this same yesterday with one user only. Now everything seems to be ok for that user.

**Comment by simpasami** [comment]
![8lxzd7lCxg5XyLf7mFprzihKeP3VaIi3Jw](https://user-images.githubusercontent.com/117338882/214845494-f9296987-cd3b-425e-ad06-bf4f09037816.png)

**Comment by simpasami** [comment]
Again same user got same problem

**Comment by paulffrench** [comment]
Hi, 

Can you confirm you are using the latest release: 1.39.07 (Build 2022101201) on your site?

Kind regards,

Paul

**Comment by simpasami** [comment]
Yes, we have latest version.

br, Sami

**Comment by learningtechnologyservices** [comment]
Fixed, and [details left in this PR request 20](https://github.com/brickfield/moodle-mod_board/pull/20).
