### ISSUE TITLE
missing thirdpartylibs.xml

### ISSUE THREAD

**Issue by danmarsden** [brickfield/moodle-mod_board#2]
When including an external library in your plugin, you must include a thirdpartylibs.xml file that includes the name, location and license of the library.
this library needs to be covered in this file:
https://github.com/brickfield/moodle-mod_board/blob/main/amd/src/jquery.editable.amd.js

More information on this is here:
https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml
And here:
https://docs.moodle.org/dev/Plugin_with_third_party_libraries

One of the other advantages of using this is that Moodle's codechecker automatically ignores any files included in the location specificed in the thirdpartylibs.xml file.

Please note - this is typically a blocker for approval in the plugins db.

**Comment by mchurchward** [comment]
Handled https://github.com/brickfield/moodle-mod_board/commit/7a0965a47d89a3823c17a401d9d93b7c4510484f
