### ISSUE TITLE
Access for guest user

### ISSUE THREAD

**Issue by ralf-krause** [brickfield/moodle-mod_board#21]
I can‘t see the board as a guest user. The Moodle course is open for guests and the activity is not hidden.

**Comment by learningtechnologyservices** [comment]
HI Ralf,

With the limited funding, It was a design choice to not make the activity available to guests. 

If someone comes up with funding and is happy to cover that feature, then that may be possible to allow in the future.

Regards

Gavin (sharedgithub login) :)
