### ISSUE TITLE
no wrap text for long words

### ISSUE THREAD

**Issue by christina-roperto** [brickfield/moodle-mod_board#22]
If the word is very long eg: Taumatawhakatangihangakoauauotamateapokaiwhenuakitanatahu it will break the board. Please see example here:

![mod_board_no_wrap](https://user-images.githubusercontent.com/22886026/144522196-ddcd33b7-a3cf-4feb-8291-f8122a3ff94a.png)

**Comment by learningtechnologyservices** [comment]
Hi Christina,

Many thanks for reporting this issue, we are confident it has been resolved by [this commit here](https://github.com/brickfield/moodle-mod_board/commit/fb6abecab89c79702a98289d362ac699f97842c1). This now correctly wraps long text both in the main board view and in the modal post views.

Kind regards
Karen
