### ISSUE TITLE
Guest user access

### ISSUE THREAD

**Issue by keithwn** [brickfield/moodle-mod_board#24]
Hi
Love the Moodle Board plugin - but I can't find a way of enabling it for guest access. 

If I enable the guest enrolement method when guests access the course the Block activity is hidden

In permissons for the course I have tried adding the Guest user to:

**Activity: Board 
Manage columns and manage all posts.
View board content and manage own posts**

but this does not solve the issue

Is there any way of solving this so that the plugin works like others please?

Thanks

Keith

**Comment by learningtechnologyservices** [comment]
HI Keith,.

With the limited funding, It was a design choice to not make the activity available to guests.

Adding Guest view - and a guest option for posting is in the roadmap. However there are oversight challenges allowing someone post images without being logged in, or other content.

If someone comes up with funding and is happy to cover that feature after the other priorities in the roadmap, then that may be possible to allow in the future.

So far funding has come from DCU, AIT, UCL and Brickfield (for some features we also needed)

Regards

Gavin (not karen)

**Comment by keithwn** [comment]
Thanks a million Gavin

Totally understand

At least I know its not down to something I’ve not got right – but is a ‘feature’!

Keith
