### ISSUE TITLE
feature request: possibility to undo given rating

### ISSUE THREAD

**Issue by Urpokarhu1** [brickfield/moodle-mod_board#26]
Hello,

When you rate a post you cannot unrate it, I would like to see an feature where you could undo given rating.

**Comment by learningtechnologyservices** [comment]
Hi there,

Many thanks for suggesting this feature, we are confident it has been resolved by [this commit here](https://github.com/brickfield/moodle-mod_board/commit/d7dfcc0b20d58f950a20815b68bd41ae560062f4). This now correctly allows users to add or remove a ranking to a post.

Kind regards
Karen
