### ISSUE TITLE
feature request: embeding board (iframe) in label

### ISSUE THREAD

**Issue by mathildemenoret** [brickfield/moodle-mod_board#30]
Hello,
Thanks a lot for this great plugin! Another request in my school... we would appreciate to be able to embed the board in the course description or in a label for example, to be visible in main page. I don't know if it is already implemented (how?) or not... Thanks a lot!

**Comment by cwarwicker** [comment]
I've implemented this feature in the linked Pull Request, for Brickfield to decide if they want or not.
