### ISSUE TITLE
Bug: manager-role cannot add rows by default

### ISSUE THREAD

**Issue by Urpokarhu1** [brickfield/moodle-mod_board#33]
manager-role cannot add rows by default, mod/board:manageboard is not allowed by default for managers

**Comment by paulffrench** [comment]
Hi,

Can you confirm you are using the latest release: 1.xx.xx (Build 2022101201) on your site please? 

Kind regards,

Paul

**Comment by learningtechnologyservices** [comment]
Closing this as the requested capability has been set for managers by default since March 2022.
