### ISSUE TITLE
feature request: edit icon

### ISSUE THREAD

**Issue by ptramonti** [brickfield/moodle-mod_board#34]
It is not very intuitive (and it is not even documented) that to change the column heading and to edit a post it is necessary to double click on it. I suggest you put an edit icon (fa-edit) near the post delete icon and to the right of the heading.
Thanks

**Comment by learningtechnologyservices** [comment]
This is in the roadmap - to have move and edit icons beside vote and delete.

**Comment by mchurchward** [comment]
This has been added in the latest releases.
