### ISSUE TITLE
feature request: add ability to move columns

### ISSUE THREAD

**Issue by djtilo-ol** [brickfield/moodle-mod_board#35]
Dear team,
We appreciate the plugin greatly here in Germany as it is a GDPR compliant and easy to use alternative to padlet - excellent!
Is there a possibility to add the option to move columns after initial adding of a column? Especially after a brainstorming phase it could prove handy to be able to move the columns.
Renaming a column and then moving all the posts can only be a workaround for a certain time. Maybe we have missed a switch?
Regards,
John Alistair

**Comment by learningtechnologyservices** [comment]
Hi there,

Thanks for the suggestion. this is in the roadmap when more funding comes through. However it is quite far down the roadmap of features.

Gavin.

**Comment by djtilo-ol** [comment]
Hi,
great, how much money are we talking about? Can you contact me through GitHub or where can I get contact details to you?
Regards from Germany,
John Alistair

**Comment by learningtechnologyservices** [comment]
The way we operate, is that we accept funding in 5,000 euro at a time. Then the next set of roadmap items get developed until the funding is up. We do not do funding "per feature" since that just gets messy for small amounts.

Gavin

**Comment by djtilo-ol** [comment]
Ok, is there an open access to the roadmap, so that I can pass it on?
John Alistair

**Comment by mchurchward** [comment]
The ability to move columns exists in the current releases.
