### ISSUE TITLE
Direct links to the activity and images in the description does not work after restoring a course

### ISSUE THREAD

**Issue by superfoght** [brickfield/moodle-mod_board#36]
Hi, I have worked on a project using this extension, and it works nicely but I'm afraid we ran into a bit of an issue when restoring backups of courses using this plugin, to a new course. 

I have tried explaining it in this video, since it was a bit difficult to explain in writing: https://www.loom.com/share/35daf25d86774d2cb99fbe7673c0f6e9

**Comment by ralfhilg** [comment]
I can confirm the issue. 

In backup the internal URL is not resolved with a placeholder:

![Unbenannt](https://user-images.githubusercontent.com/41056305/192882227-39cf7e05-b62b-4662-ba35-b8ff738afd18.PNG)

**Comment by ralfhilg** [comment]
I've analysed the backup file.  The main reason is that the file is not included in the backup. The link to the file would work if it is included in the backup.  Please check the backup process. 
I've tested it with other activities and with links to external file locations. Other types of activities add the file to the backup. If the file is located external its visible after restoring correct.

**Comment by rrusso** [comment]
Is there any movement on this?

**Comment by brickfieldlabs** [comment]
Yes, we should look at doing an updated release  in next two weeks with various fixes and changes.

G

**Comment by learningtechnologyservices** [comment]
Hi there,

Many thanks for reporting this issue, we are confident it has been resolved by [this commit here](https://github.com/brickfield/moodle-mod_board/commit/947d9a60a2bbb7c2a8deb3f83dde4225497980d3). This now correctly backs up all internal site file and links data.

Kind regards
Karen
