### ISSUE TITLE
feature: youtube only if allowed

### ISSUE THREAD

**Issue by andreasschenkel** [brickfield/moodle-mod_board#38]
Note: Feature is implemented an a pull request will follow.

Description:
In some institutions videos should be stored in own streaming plattforms and not in youtube.
There are other issues where you to not want to be able to embed videos from youtube.
New feature request: Add a setting to be able to deactivate the youtube button or the selection in the dropdown-list.

**Comment by mchurchward** [comment]
Feature has been added. Thanks.
