### ISSUE TITLE
Invalid get_string() identifier: 'modulename' or component 'board'. Perhaps you are missing $string['modulename'] = ''; in mod/board/lang/en/board.php?

### ISSUE THREAD

**Issue by caiadogithub** [brickfield/moodle-mod_board#42]
Moodle 3.11.7
PostgreSQL 12
PHP7.4

---------------------

Invalid get_string() identifier: 'modulename' or component 'board'. Perhaps you are missing $string['modulename'] = ''; in mod/board/lang/en/board.php?

    line 356 of /lib/classes/string_manager_standard.php: call to debugging()
    line 7354 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
    line 137 of /blocks/sharing_cart/lib/settingslib.php: call to get_string()
    line 40 of /blocks/sharing_cart/settings.php: call to admin_setting_configmulticheckboxmodtypes->__construct()
    line 122 of /lib/classes/plugininfo/block.php: call to include()
    line 81 of /admin/settings/plugins.php: call to core\plugininfo\block->load_settings()
    line 8927 of /lib/adminlib.php: call to require()
    line 19 of /admin/settings.php: call to admin_get_root()

**Comment by learningtechnologyservices** [comment]
Hi there, Caiadog, the string is definitely present in the [board plugin's github repository here](https://github.com/brickfield/moodle-mod_board/blob/f88faf8b4d93acddcbbd5dda9ce9c323ab45171b/lang/en/board.php#L28).

You may need to check if you're using a different language to English, and have you done a Purge Caches on your site after installing the plugin?
