### ISSUE TITLE
Moodle 4.0: description of the activity is shown twice.

### ISSUE THREAD

**Issue by ralfhilg** [brickfield/moodle-mod_board#44]
The plugin is available for 3.11. 
In version 4.0 the description is shown twice for the users. See 'Testtext' in the screenshot

Are there any plans for a 4.0 version of the plugin.

![image](https://user-images.githubusercontent.com/41056305/189343358-b27a4276-51be-4102-8dd7-4d9ca9cfc881.png)

**Comment by mchurchward** [comment]
This has been [fixed](https://github.com/brickfield/moodle-mod_board/commit/45a8d44991df535b04610a402c684011af658940) for 4.*.
