### ISSUE TITLE
PHP8.0

### ISSUE THREAD

**Issue by aspark21** [brickfield/moodle-mod_board#47]
Moodle 4.2dev
PHP8.0
mod_board: main

    1) core\externallib_test::test_all_external_info with data set "mod_board_get_board" (stdClass Object (...))
    Unexpected debugging() call detected.
    Debugging: External function parameters: invalid OPTIONAL value specified.
    * line 729 of /lib/externallib.php: call to debugging()
    * line 91 of /mod/board/external.php: call to external_function_parameters->__construct()
    * line 122 of /lib/externallib.php: call to mod_board_external::get_board_parameters()
    * line 440 of /lib/tests/externallib_test.php: call to external_api::external_function_info()
    * line 1548 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to core\externallib_test->test_all_external_info()
    * line 1154 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit\Framework\TestCase->runTest()
    * line 80 of /lib/phpunit/classes/advanced_testcase.php: call to PHPUnit\Framework\TestCase->runBare()
    * line 728 of /vendor/phpunit/phpunit/src/Framework/TestResult.php: call to advanced_testcase->runBare()
    * line 904 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit\Framework\TestResult->run()
    * line 673 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit\Framework\TestCase->run()
    * line 673 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit\Framework\TestSuite->run()
    * line 673 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit\Framework\TestSuite->run()
    * line 673 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit\Framework\TestSuite->run()
    * line 661 of /vendor/phpunit/phpunit/src/TextUI/TestRunner.php: call to PHPUnit\Framework\TestSuite->run()
    * line 144 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit\TextUI\TestRunner->run()
    * line 97 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit\TextUI\Command->run()
    * line 98 of /vendor/phpunit/phpunit/phpunit: call to PHPUnit\TextUI\Command::main()
    * line 123 of /vendor/bin/phpunit: call to include()
  
  
    /var/www/html/lib/phpunit/classes/advanced_testcase.php:88

**Comment by mchurchward** [comment]
Hi. Thanks for the report. We won't be looking at 4.2 support for a few months. The same tests do pass on [Moodle 4.0](https://github.com/brickfield/moodle-mod_board/actions/runs/3542344776) and [Moodle 4.1](https://github.com/brickfield/moodle-mod_board/actions/runs/3677156758).

**Comment by durzo** [comment]
Getting this with Moodle 4.1.3 and PHP8.0 when visiting `/admin/webservice/documentation.php`
```
External function parameters: invalid OPTIONAL value specified.
line 729 of /lib/externallib.php: call to debugging()
line 91 of /mod/board/external.php: call to external_function_parameters->__construct()
line 122 of /lib/externallib.php: call to mod_board_external::get_board_parameters()
line 36 of /admin/webservice/documentation.php: call to external_api::external_function_info()
```

**Comment by mchurchward** [comment]
I believe #62 fixes this issue. We'll merge it in.

**Comment by learningtechnologyservices** [comment]
Hi there,

Many thanks for reporting this issue, we are confident it has been resolved by [this commit here](https://github.com/brickfield/moodle-mod_board/commit/1737ad104f974522bd5eae3738bad3c1ee7763a0). This now correctly processes the external service parameters.

Kind regards
Karen
