### ISSUE TITLE
3.11 web service documentation error

### ISSUE THREAD

**Issue by aspark21** [brickfield/moodle-mod_board#48]
mod_board: MOODLE_311_STABLE
Moodle: latest MOODLE_311_STABLE
page affected: your.moodle.site/admin/webservice/documentation.php

External function parameters: invalid OPTIONAL value specified.
line 729 of /lib/externallib.php: call to debugging()
line 91 of /mod/board/external.php: call to external_function_parameters->__construct()
line 122 of /lib/externallib.php: call to mod_board_external::get_board_parameters()
line 36 of /admin/webservice/documentation.php: call to external_api::external_function_info()

**Comment by NeillM** [comment]
I'm seeing the same error on the Moodle 4.1 version of the plugin

**Comment by paulffrench** [comment]
Hi,

Could you provide steps for replication please.

Kind regards,

Paul

**Comment by NeillM** [comment]
Assuming you are on Moodle 4.1 

Ensure you have the Mobile App web service enabled, and that developer debugging is enabled on the site

The quickest way to developer debuging will be to add the following to your config.php

`$CFG->debug = (E_ALL | E_STRICT);`
`$CFG->debugdisplay = 1;`

You would navigate to: Site administration > Server > Web services > API documentation

**Comment by opitz** [comment]
The issue also remains with MOODLE_402_STABLE and the issue can be seen according to Neill's procedure.

**Comment by aspark21** [comment]
this also gets trigerred via phpunit tests:

core\externallib_test::test_all_external_info with data set "mod_board_get_board" (stdClass Object (...))
Unexpected debugging() call detected.
Debugging: External function parameters: invalid OPTIONAL value specified.
* line 729 of /lib/externallib.php: call to debugging()
* line 91 of /mod/board/external.php: call to external_function_parameters->__construct()
* line 122 of /lib/externallib.php: call to mod_board_external::get_board_parameters()
* line 440 of /lib/tests/externallib_test.php: call to external_api::external_function_info()
* line 1548 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to core\externallib_test->test_all_external_info()
* line 1154 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit\Framework\TestCase->runTest()
* line 80 of /lib/phpunit/classes/advanced_testcase.php: call to PHPUnit\Framework\TestCase->runBare()
* line 728 of /vendor/phpunit/phpunit/src/Framework/TestResult.php: call to advanced_testcase->runBare()
* line 904 of /vendor/phpunit/phpunit/src/Framework/TestCase.php: call to PHPUnit\Framework\TestResult->run()
* line 673 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit\Framework\TestCase->run()
* line 673 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit\Framework\TestSuite->run()
* line 673 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit\Framework\TestSuite->run()
* line 673 of /vendor/phpunit/phpunit/src/Framework/TestSuite.php: call to PHPUnit\Framework\TestSuite->run()
* line 661 of /vendor/phpunit/phpunit/src/TextUI/TestRunner.php: call to PHPUnit\Framework\TestSuite->run()
* line 144 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit\TextUI\TestRunner->run()
* line 97 of /vendor/phpunit/phpunit/src/TextUI/Command.php: call to PHPUnit\TextUI\Command->run()
* line 97 of phpvfscomposer:///vendor/phpunit/phpunit/phpunit: call to PHPUnit\TextUI\Command::main()
* line 118 of /vendor/bin/phpunit: call to include()


/var/www/html/lib/phpunit/classes/advanced_testcase.php:88
phpvfscomposer:///var/www/html/vendor/phpunit/phpunit/phpunit:97

**Comment by learningtechnologyservices** [comment]
Hi there,

Many thanks for reporting this issue, we are confident it has been resolved by [this commit here, contributed by NeillM](https://github.com/brickfield/moodle-mod_board/commit/1737ad104f974522bd5eae3738bad3c1ee7763a0). This now correctly allocates and processes the external service parameters for submitting and retrieving posts.

Kind regards
Karen
