### ISSUE TITLE
Compatibility with legacy logging

### ISSUE THREAD

**Issue by sgodbehere01** [brickfield/moodle-mod_board#49]
Hi there,

As per the attached, we are seeing an error when legacy logging is enabled on Moodle which occurs even as debugging is set to "None". Currently legacy logging is needed for the functionality of an external system. Upon closing the error and refreshing the page the post does seem to be added, however the error itself is quite alarming for students and staff. Is there the possibility of the plugin being patched to allow the usage of legacy logging?

![Screenshot_from_2023-01-30_11-06-46](https://user-images.githubusercontent.com/31889885/215490848-7177e08a-41d1-44b5-96ba-14e0a44b38b0.png)

Kind regards,

Sam

**Comment by paulffrench** [comment]
Hi, 

Could you provide replication instructions and the full stack trace as well please.

Kind regards,

Paul

**Comment by learningtechnologyservices** [comment]
Closing, deprecated get_legacy_logdata in 4.2, not available as a logging option anymore.
