### ISSUE TITLE
Board->name used in file name unfiltered

### ISSUE THREAD

**Issue by danmarsden** [brickfield/moodle-mod_board#5]
might need strip tags or some form of cleaning in there before you use it in a filename?
https://github.com/brickfield/moodle-mod_board/blob/main/download_board.php#L42

**Comment by danmarsden** [comment]
another one - you might need to check for others:/
https://github.com/brickfield/moodle-mod_board/blob/main/download_submissions.php#L42

**Comment by mchurchward** [comment]
Handled https://github.com/brickfield/moodle-mod_board/commit/7a0965a47d89a3823c17a401d9d93b7c4510484f
