### ISSUE TITLE
Writing long message causes error/formsubmissioninvalid in version 1.39.07

### ISSUE THREAD

**Issue by jarvil1** [brickfield/moodle-mod_board#50]
Hello,

There is a bug in 1.39.07 (Build 2022101201) that is not present in version 1.39.06 when you try for the first time type a very long message to a new board it gives an error error/formsubmissioninvalid This problem will go away if you delete your browser cache.

```
formsubmissioninvalid
error/formsubmissioninvalid
File: /mod/board/external.php
Line: 397
Stack trace:

Error code: formsubmissioninvalid $a contents: 
* line 397 of /mod/board/external.php: moodle_exception thrown 
* line 261 of /lib/externallib.php: call to mod_board_external::submit_form() 
* line 81 of /lib/ajax/service.php: call to external_api::call_external_function() 
```

![error2](https://user-images.githubusercontent.com/53904029/222070260-227bd719-a907-4c94-92d3-bccaea127339.png)

Steps to repeat

1. Clear your browser cache
2. Create a new course and add a user as a teacher to it
3. as an administrator use "login as" option and select this teacher
4. Now as an teacher open this new course and add a new board with default settings
5. in the first row try to add a new message with title and message

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec dictum sollicitudin blandit. Nam cursus eros ipsum, vel consequat leo efficitur eget. Praesent sed nibh a ligula aliquet mollis. Curabitur aliquet suscipit leo at facilisis. Sed lorem turpis, lobortis id maximus at, viverra sed nunc. Suspendisse commodo dolor eget elit pulvinar sollicitudin. Duis vel odio lacus. Vestibulum tristique, diam non consectetur sodales, ligula est mattis quam, id molestie neque lectus quis sapien. Duis ullamcorper diam neque, nec dictum neque efficitur vel. Pellentesque suscipit orci vitae libero maximus, sed scelerisque mauris fringilla. Praesent ornare malesuada turpis at venenatis. Quisque faucibus turpis a imperdiet hendrerit. Nam iaculis pellentesque viverra. Vestibulum egestas nibh purus, non volutpat lorem facilisis id. Vestibulum convallis sollicitudin lacus, et iaculis mauris congue eu.

Cras ultrices sem est. Pellentesque id purus vel ligula pulvinar molestie a in dolor. Suspendisse eleifend tellus at mauris ornare molestie. Maecenas non massa eget diam lobortis hendrerit. Vestibulum ante ipsum primis in faucibus orci luctus. 
````
6. Notice how you get an error

**Comment by learningtechnologyservices** [comment]
Hi there,

Many thanks for reporting this issue, we are confident it has been resolved by [this commit here](https://github.com/brickfield/moodle-mod_board/commit/1737ad104f974522bd5eae3738bad3c1ee7763a0). This now correctly allocates and processes the external service parameters for submitting and retrieving posts.

Kind regards
Karen
