### ISSUE TITLE
Moodle 4.1: Title and link to board page are not showing when embedded on course main page

### ISSUE THREAD

**Issue by cdipe** [brickfield/moodle-mod_board#53]
In Moodle 4.1 with Board 2022040105, the board Title and the link to board page are not showing when the board is embedded on course main page.
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/14754240/224301241-d47bc1fe-1a12-4a53-bde7-6db5f28a55de.png">

<img width="800" alt="image" src="https://user-images.githubusercontent.com/14754240/224301993-437650ae-8ff7-4839-9502-57b7232729a7.png">

**Comment by brickfieldlabs** [comment]
Noted, will add to explore in coming releases.

**Comment by learningtechnologyservices** [comment]
Hi there

This issue has been fixed by [our db72f4a commit here](https://github.com/brickfield/moodle-mod_board/commit/db72f4a47741f1c97175e0d65c6795d07071fc12), so I'm closing this now.

Many thanks again for reporting this issue, and helping us with our Board improvements!

Kind regards
Karen
