### ISSUE TITLE
Moodle 4.1 & mod_board 1.400.01 post and cancel buttons are in the wrong order

### ISSUE THREAD

**Issue by jarvil1** [brickfield/moodle-mod_board#55]
Hello,
There seems to be a bu in mod_board 1.400.01 (Build 2022101201) when you write a new message to a row the post and cancel buttons are in the wrong order 

- cancel, post
when before they were
- post, cancel

to which all users are used to.

![image](https://user-images.githubusercontent.com/53904029/225556757-ffcbe8d6-ea8c-4f75-98cc-1615240d5de4.png)

**Comment by learningtechnologyservices** [comment]
Hi there,

Many thanks for reporting this issue, we are confident it has been resolved by [this commit here](https://github.com/brickfield/moodle-mod_board/commit/0a175e23779f786965e8865d8e7090836dcd3bb1). While either order is valid accessibly, we appreciate that this follows the Moodle standard, and have updated this accordingly.

Kind regards
Karen
