### ISSUE TITLE
The activity will not work well with Moodle's context locking

### ISSUE THREAD

**Issue by NeillM** [brickfield/moodle-mod_board#59]
When context locking is enabled in Moodle and the context that a Board activity is in is locked users will not be able to see anything in the board.

This will happen because:

1. Context locking makes all checks for write capabilities return false.
2. All the capabilities in the plugin are write capabilities

I can see that the 'mod/board:view' is actually used as a write capability when:

1. Creating notes
2. Rating notes

It is probably worth splitting these uses off into new capabilities.

**Comment by NeillM** [comment]
While working on a fix I realised that rating probably could use the same capability as posting, since who can rate is controlled by a setting in the plugin.

I also noticed that users would be able to delete their posts when they no longer had the capability to post (as would be the case when contexts are frozen)

**Comment by learningtechnologyservices** [comment]
Hi @NeillM , many thanks for your great context freezing update for Board, which we have now merged here in [commit 2b6702e](https://github.com/brickfield/moodle-mod_board/commit/2b6702ee310ee31d901d1bdc3194c2838197e197)!
