### ISSUE TITLE
function included in in-line file

### ISSUE THREAD

**Issue by danmarsden** [brickfield/moodle-mod_board#6]
normally functions should not be mixed into in-line files and should really be using frankenstyle naming conventions or namespaced:
https://github.com/brickfield/moodle-mod_board/blob/main/download_board.php#L73

this one probably wouldn't be a blocker for approval in the plugins db.

**Comment by danmarsden** [comment]
another one:
https://github.com/brickfield/moodle-mod_board/blob/main/download_submissions.php#L71

**Comment by mchurchward** [comment]
Handled https://github.com/brickfield/moodle-mod_board/commit/7a0965a47d89a3823c17a401d9d93b7c4510484f
