### ISSUE TITLE
Allow empty grouping selection

### ISSUE THREAD

**Issue by Snowdle** [brickfield/moodle-mod_board#60]
When using a group mode, it is currently not allowed to select "none" in the Grouping field. This should be changed, making it possible to select "none" to show all groups - this will also better reflect the functionality of other modules like Assignment, which already allows "none" selection

**Comment by chschlegel** [comment]
We have the same problem. Groups can not be seperated in the common moodle way. This is a very important basic functionality in most of our courses.

Please address this soon, it shouldn't be a big deal technically.
Thank you!

**Comment by learningtechnologyservices** [comment]
Hi there @Snowdle and @chschlegel ,

Many thanks for reporting this issue, we are confident it has been resolved by [this commit here](https://github.com/brickfield/moodle-mod_board/commit/12b9d48c6e671d992f0fc5ecfc190a3adfb80f29).

Kind regards
Karen

**Comment by chschlegel** [comment]
thanks a lot, it works great!

**Comment by JL-MM** [comment]
Hello, any plans to add a new release to Moodle.org? The last update was 25th November 2022. This is a problem we have with the old version and this fix would solve the issue.

**Comment by brickfieldlabs** [comment]
Yes,. next week is the goal :)
