### ISSUE TITLE
Make board-embedding configurable

### ISSUE THREAD

**Issue by christianwolters** [brickfield/moodle-mod_board#63]
Hi, 

as discussed in #56, I'd like to add an admin setting to enable/disable board embedding globally.

This is the refined user story:

As an administrator,
I want to decide if the board embedding feature is available on my moodle instance

**Comment by learningtechnologyservices** [comment]
This has been integrated to [Board here](https://github.com/brickfield/moodle-mod_board/commit/356e86b55b5faedbb45cb4ec63281492c9b44e58), thanks for your contribution @christianwolters ! Closing.
