### ISSUE TITLE
board-name output in raw form in heading

### ISSUE THREAD

**Issue by danmarsden** [brickfield/moodle-mod_board#7]
https://github.com/brickfield/moodle-mod_board/blob/main/view.php#L79

should probably use format_string for multi-lang content etc.

**Comment by danmarsden** [comment]
bit weird seeing h2's there too - maybe it could be using $OUTPUT->heading instead?

**Comment by mchurchward** [comment]
Handled https://github.com/brickfield/moodle-mod_board/commit/7a0965a47d89a3823c17a401d9d93b7c4510484f

**Comment by danmarsden** [comment]
Heading() doesnt pass it through format_string though does it? You might need to pass it through format_string if you want the name to be compatible with multi-lang.   (I'm reading this on my phone so could have missed something...)

**Comment by danmarsden** [comment]
See here for an example: https://github.com/moodle/moodle/blob/3610f1ee3b3da37140a7641af602bb5e3c8ba1bb/mod/h5pactivity/view.php#L71

**Comment by mchurchward** [comment]
I assumed it did. I seems like something obvious it should do seeing as every module's name is supposed to be the heading.
But, looks like you're right.
