### ISSUE TITLE
Feature Request: Adminsetting to enforce use of public boards

### ISSUE THREAD

**Issue by JayBraker** [brickfield/moodle-mod_board#70]
Hi everyone

after internal discussions we have concluded that we must disable to feature "SINGLEUSER_PUBLIC" boards entirely.
Unfortunately it poses a privacy risk for enrolled students as their names will be shown in the dropdown.

As we are about to disable the feature in a local fork, I thought maybe this option is of interest to others in the community?

Kind regards,
Josha

**Comment by learningtechnologyservices** [comment]
Hi @JayBraker ,

After reviewing your feature request, we believe that this is a reasonable configuration, in keeping with the student anonymity and privacy that we encourage with Board usage.

If you have already done a code patch for this, we would be happy to review it and add it to the main github repository.

Many thanks in advance
Karen

**Comment by learningtechnologyservices** [comment]
We could also look at an option to anonymise students' names in the displayed dropdown, if that would an acceptable alternative?

**Comment by JayBraker** [comment]
Yes, both would be acceptable to us, I guess the latter is really a nicer solution to this issue.

As we want to deploy the updatesoon, I would make necessary changes to disable public boards for now.
If this is of interest to you we can contribute in form of a PR

**Comment by JayBraker** [comment]
https://github.com/JayBraker/moodle-mod_board/tree/MOODLE_400_STABLE-issue-70

Is currently failing unittests for MOODLE_402_STABLE (so does the current MOODLE_400_STABLE branch of this repo :/) but should provide the basic abilty disallow use of single user modes `public` or `private`.

Also rebased the changes for your current main branch
https://github.com/JayBraker/moodle-mod_board/tree/main-issue-70

**Comment by learningtechnologyservices** [comment]
Hi @JayBraker , many thanks for contributing your great feature to configure singleuser settings, which we have [added to the github repository here](https://github.com/brickfield/moodle-mod_board/commit/1e60c1d8bf73e6496aa56d1b1dec6d4d078acbf1), due to some changes to our other Board files!
