### ISSUE TITLE
formsubmissioninvalid for new entries

### ISSUE THREAD

**Issue by cre-eledia** [brickfield/moodle-mod_board#71]
On version1.400.01 (Build 2022101201) running on a Moodle Workplace 4.1.3 Build: 20230425 we get the following error:

```
formsubmissioninvalid
error/formsubmissioninvalid
Datei: /mod/board/external.php
Zeile: 397
Stack trace:
Error code: formsubmissioninvalid
$a contents:
* line 397 of /mod/board/external.php: moodle_exception thrown
* line 261 of /lib/externallib.php: call to mod_board_external::submit_form()
* line 86 of /lib/ajax/service.php: call to external_api::call_external_function()
```

for  new entries in the board and only for certain users. Problem is difficult to reproduce. It seems not to be dependent on the form of the entry (number of chars in title or text). It happens to Adminusers, so seems not to be capability related. 

Problem might be in some relationship to https://github.com/brickfield/moodle-mod_board/issues/50.

Any ideas?

**Comment by learningtechnologyservices** [comment]
Hi there,

Many thanks for reporting this issue, we are confident it has been resolved by [this commit here](https://github.com/brickfield/moodle-mod_board/commit/e14fcb5a0458f38f361e5c7a26aafe579f4144a3#diff-cc3e3f1609f1abfba5ff62fe877b1ced25ef264b12ac5c88ad27180414ba4629R60). This now correctly retrieves the admin-configured max length for the post to allow the correct length post to be processed.

Kind regards
Karen
