### ISSUE TITLE
Pop up to write a new post for column won't close after posting

### ISSUE THREAD

**Issue by kirsten-k** [brickfield/moodle-mod_board#79]
When I want to write a new post for column, a pop-up opens. After I have clicked on 'Post', the pop-up unfortunately does not close, but reloads (?) and is empty again.

(Moodle 4.1)

**Comment by learningtechnologyservices** [comment]
Hi @kirsten-k (Kirsten), thanks for reporting your issue with creating posts on your Board instance.

Would it be possible to include more details to help us to replicate this issue, as we are currently unable to do so?

The following would be very useful:
- The global settings of the board plugin, all of them if possible
- The settings of the board instance, all of them if possible.
- The exact content you are trying to add to the post.
- If possible, a short video of the post not getting submitted correctly can be very helpful also.

If you're happier to share this information privately, that's fine, our [Brickfield profile is here](https://moodle.org/message/index.php?id=4074596#) that you can send a message to.

**Comment by kirsten-k** [comment]
Board Plugin mod_board
1.400.01 (Build 2022101201)
2022040105
All global settings are default. Nothing changed.

Unfortunately, I cannot reproduce the bug. It happened in Mozilla Firefox. Now, everything ist fine.

**Comment by learningtechnologyservices** [comment]
Hi Kirsten, many thanks for your follow-up and thanks for helping us to triage this, if this reoccurs, please reopen this and we'll investigate further.
