### ISSUE TITLE
constants should be prefixed by "BOARD"

### ISSUE THREAD

**Issue by danmarsden** [brickfield/moodle-mod_board#8]
https://github.com/brickfield/moodle-mod_board/blob/main/classes/board.php#L28-L36

these should all probably be prefixed by "BOARD_" or "MOD_BOARD" as per:
https://docs.moodle.org/dev/Frankenstyle#Constants

**Comment by mchurchward** [comment]
Handled in [this commit](https://github.com/brickfield/moodle-mod_board/commit/7a0965a47d89a3823c17a401d9d93b7c4510484f).
