### ISSUE TITLE
Bug: eMail in download_submissions.php should respect setting hiddenuserfields and capability moodle/course:viewhiddenuserfields

### ISSUE THREAD

**Issue by andreasschenkel** [brickfield/moodle-mod_board#98]
If eMail is a hidden userfield and the user has not the capability moodle/course:viewhiddenuserfields then the email-adress should not be included in the download of submissions.

**Comment by andreasschenkel** [comment]
Will try to create a pull-request soon.

**Comment by learningtechnologyservices** [comment]
Dealt with in [commit here](https://github.com/brickfield/moodle-mod_board/commit/70b823a7e3c5ababcbc10c427f253f919c21f6b8). Closing.
